
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE DELETED IS NULL
AND NOT DISABLED
ORDER BY NAME;

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE DELETED IS NULL
AND NOT DISABLED
AND TYPE IN ('SERVICE', 'LEGACY_SERVICE')
ORDER BY NAME;

SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
WHERE DELETED IS NULL
AND NOT DISABLED
AND TYPE IN ('PERSON')
ORDER BY NAME;
